config/routes.rb
Rails.application.routes.draw do
  resources :tips
  resources :posts
  resources :reviews
  resources :profiles
  devise_for :users

  root 'posts#index'
  get 'notes' => 'home#notes'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :platform, presence: true
  validates :region, presence: true
  validates :tag, presence: true, uniqueness: true
  validates :sr, presence:true
  validates :roles, presence: true

  serialize :roles, Array

  belongs_to :user

  enum platform: [:pc, :xbl, :psn]
  enum region: [:us, :eu]

  # TODO: validate that platform + region + tag is an actual account, assign SR
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:user_id, :platform, :region, :tag, :sr, :reputation, :roles)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.haml
= form_for @profile do |f|
  - if @profile.errors.any?
    #error_explanation
      %h2= "#{pluralize(@profile.errors.count, "error")} prohibited this profile from being saved:"
      %ul
        - @profile.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :platform
    = f.number_field :platform
  .field
    = f.label :region
    = f.number_field :region
  .field
    = f.label :tag
    = f.text_field :tag
  .field
    = f.label :sr
    = f.text_field :sr
  .actions
    = f.submit 'Save'

app/views/profiles/edit.html.haml
%h1 Editing profile

= render 'form'

= link_to 'Show', @profile
\|
= link_to 'Back', profiles_path

app/views/profiles/index.html.haml
%h1 Listing profiles

%table
  %thead
    %tr
      %th Platform
      %th Region
      %th Tag
      %th Sr
      %th
      %th
      %th

  %tbody
    - @profiles.each do |profile|
      %tr
        %td= profile.platform
        %td= profile.region
        %td= profile.tag
        %td= profile.sr
        %td= link_to 'Show', profile
        %td= link_to 'Edit', edit_profile_path(profile)
        %td= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Profile', new_profile_path

app/views/profiles/new.html.haml
%h1 New profile

= render 'form'

= link_to 'Back', profiles_path

app/views/profiles/show.html.haml
%p#notice= notice

%p
  %b Platform:
  = @profile.platform
%p
  %b Region:
  = @profile.region
%p
  %b Tag:
  = @profile.tag
%p
  %b Sr:
  = @profile.sr

= link_to 'Edit', edit_profile_path(@profile)
\|
= link_to 'Back', profiles_path