config/routes.rb
Rails.application.routes.draw do
  resources :tips
  resources :posts
  resources :reviews
  resources :profiles
  devise_for :users

  root 'posts#index'
  get 'notes' => 'home#notes'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  paginates_per 5

  belongs_to :profile
  has_many :reviews, dependent: :destroy
  has_one_attached :video, dependent: :destroy
  has_one_attached :thumbnail, dependent: :destroy

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }

  serialize :coachability, Array

  # TODO: link validation.
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  include PostsHelper

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(created_at: :desc).page params[:page]
    @number_of_posts = Post.all.length
    # @recommended_posts = []
    #
    # if current_user && has_profile?(current_user)
    #   user_profile = Profile.find(current_user.id)
    #   Post.all.each do |post|
    #     poster_profile = Profile.find(post.profile_id)
    #     if poster_profile.sr < user_profile.sr
    #       role_match = []
    #       poster_profile.roles.each { |role| role_match.push(user_profile.roles.include? role) }
    #       if role_match.include? true
    #         @recommended_posts.push(post)
    #       end
    #     end
    #   end
    # end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:profile_id, :title, :link, :coachability, :video, :thumbnail)
    end
end

app/helpers/posts_helper.rb
module PostsHelper

  def get_rank(post_id)
    sr = Profile.find(Post.find(post_id).profile_id).sr

    case
    when sr < 1500
      then '1'
    when sr >= 1500 && sr < 2000
      then '2'
    when sr >= 2000 && sr < 2500
      then '3'
    when sr >= 2500 && sr < 3000
      then '4'
    when sr >= 3000 && sr < 3500
      then '5'
    when sr >= 3500 && sr < 4000
      then '6'
    when sr > 4000
      then '7'
    end
  end

  def get_profile(post_id)
    Profile.find(Post.find(post_id).profile_id)
  end

  def get_reviewer_sr(review)
    Profile.find(review.profile_id).sr
  end

  def get_poster_sr(poster)
    Profile.find(poster.profile_id).sr
  end

end

app/views/posts/_form.html.haml
= form_for @post, :html => { class: 'form-signin' } do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message

  = f.hidden_field :profile_id, value: Profile.find(current_user.id).id
  .p-3.bg-dark.text-white
    .form-group
      = f.label :title
      = f.text_field :title, class: 'form-control'
    .form-group
      = f.label :video
      = f.file_field :video, class: 'form-control-file'
    .form-group
      = f.label :thumbnail
      = f.file_field :thumbnail, class: 'form-control-file'
    -# .field
    -#   = f.label :link
    -#   = f.text_field :link
    .actions
      = f.submit 'Save', class: 'btn btn-primary btn-block font-weight-bold'

app/views/posts/edit.html.haml
%h1.p-3.mb-0.rounded-top.bg-dark.text-warning Edit post

= render 'form'

.p-3.m-0.rounded-bottom.bg-dark
  = link_to 'Show', @post, class: 'btn btn-light'
  = link_to 'Back', posts_path, class: 'btn btn-secondary'

app/views/posts/index.html.haml
#owc_feed_payload{ number_of_posts: @number_of_posts, user_profile: current_user ? Profile.find(current_user.id).to_json : nil }
#owc
= javascript_pack_tag 'owc'

app/views/posts/new.html.haml
%h1.p-3.mb-0.rounded-top.bg-dark.text-warning New post

= render 'form'

.p-3.m-0.rounded-bottom.bg-dark
  = link_to 'Back', posts_path, class: 'btn btn-secondary'

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @post.title
%p
  %b Coachability:
  = @post.coachability

= link_to 'Edit', edit_post_path(@post)

= link_to 'Back', posts_path