config/routes.rb
Rails.application.routes.draw do
  resources :tips
  resources :posts
  resources :reviews
  resources :profiles
  devise_for :users

  root 'posts#index'
  get 'notes' => 'home#notes'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @post = Post.find(params[:post])
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        render :json => @review
        format.html
      else
        render :json => @review.errors
        format.html
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        render :json => @review
        format.html
      else
        render :json => @review.errors
        format.html
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      render :json => 'Review was successfully destroyed.'
      format.html
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:profile_id, :post_id, :summary, :rating, :title)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.haml
= form_for @review do |f|
  - if @review.errors.any?
    #error_explanation
      %h2= "#{pluralize(@review.errors.count, "error")} prohibited this review from being saved:"
      %ul
        - @review.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/reviews/edit.html.haml
%h1 Editing review

= render 'form'

= link_to 'Show', @review
\|
= link_to 'Back', reviews_path

app/views/reviews/index.html.haml
%h1 Listing reviews

%table
  %thead
    %tr
      %th Coach
      %th Rating
      %th Title
      %th
      %th
      %th

  %tbody
    - @reviews.each do |review|
      %tr
        %td= review.coach
        %td= review.rating
        %td= review.title
        %td= link_to 'Show', review
        %td= link_to 'Edit', edit_review_path(review)
        %td= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Review', new_review_path

app/views/reviews/new.html.haml
-# %h1 New review
-#
-# = render 'form'
-#
-# = link_to 'Back', reviews_path

#owc_reviewer{post: @post.to_json, video_url: rails_blob_path(@post.video).to_json, current_user: Profile.find(current_user.id).to_json }
= javascript_pack_tag 'owc_reviewer'

app/views/reviews/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @review.title

= link_to 'Edit', edit_review_path(@review)
\|
= link_to 'Back', reviews_path