config/routes.rb
Rails.application.routes.draw do
  resources :tips
  resources :posts
  resources :reviews
  resources :profiles
  devise_for :users

  root 'posts#index'
  get 'notes' => 'home#notes'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tip.rb
class Tip < ApplicationRecord
  before_validation :validate_individual_tags

  belongs_to :review

  validates :timestamp, presence: true
  validates :comment, presence: true, length: { minimum: 75, maximum: 300 }
  validates :tags, length: { maximum: 10 }

  serialize :tags, Array
  serialize :helpfulness, Array

  private

  def validate_individual_tags
    self.tags.delete_if { |tag| tag.length < 3 || tag.length > 15 }

    until self.tags.length < 11
      self.tags.pop
    end
  end
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :set_tip, only: [:show, :edit, :update, :destroy]

  # GET /tips
  # GET /tips.json
  def index
    @tips = Tip.all
  end

  # GET /tips/1
  # GET /tips/1.json
  def show
  end

  # GET /tips/new
  def new
    @tip = Tip.new
  end

  # GET /tips/1/edit
  def edit
  end

  # POST /tips
  # POST /tips.json
  def create
    @tip = Tip.new(tip_params)

    respond_to do |format|
      if @tip.save
        render :json => @tip
        format.html
      else
        render :json => @tip.errors
        format.html
      end
    end
  end

  # PATCH/PUT /tips/1
  # PATCH/PUT /tips/1.json
  def update
    respond_to do |format|
      if @tip.update(tip_params)
        render :json => @tip
        format.html
      else
        render :json => @tip.errors
        format.html
      end
    end
  end

  # DELETE /tips/1
  # DELETE /tips/1.json
  def destroy
    @tip.destroy
    respond_to do |format|
      render :json => 'Tip was successfully destroyed.'
      format.html
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tip
      @tip = Tip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tip_params
      params.require(:tip).permit(:review_id, :timestamp, :comment, :helpfulness, :tags => [])
    end
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/views/tips/_form.html.haml
= form_for @tip do |f|
  - if @tip.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tip.errors.count, "error")} prohibited this tip from being saved:"
      %ul
        - @tip.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :review
    = f.text_field :review
  .field
    = f.label :timestamp
    = f.number_field :timestamp
  .field
    = f.label :comment
    = f.text_area :comment
  .field
    = f.label :helpfulness
    = f.number_field :helpfulness
  .field
    = f.label :tag
    = f.text_field :tag
  .actions
    = f.submit 'Save'

app/views/tips/edit.html.haml
%h1 Editing tip

= render 'form'

= link_to 'Show', @tip
\|
= link_to 'Back', tips_path

app/views/tips/index.html.haml
%h1 Listing tips

%table
  %thead
    %tr
      %th Review
      %th Timestamp
      %th Comment
      %th Helpfulness
      %th Tag
      %th
      %th
      %th

  %tbody
    - @tips.each do |tip|
      %tr
        %td= tip.review
        %td= tip.timestamp
        %td= tip.comment
        %td= tip.helpfulness
        %td= tip.tags
        %td= link_to 'Show', tip
        %td= link_to 'Edit', edit_tip_path(tip)
        %td= link_to 'Destroy', tip, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Tip', new_tip_path

app/views/tips/new.html.haml
%h1 New tip

= render 'form'

= link_to 'Back', tips_path

app/views/tips/show.html.haml
%p#notice= notice

-# %p
-#   %b Review:
-#   = @tip.review
-# %p
-#   %b Timestamp:
-#   = @tip.timestamp
-# %p
-#   %b Comment:
-#   = @tip.comment
-# %p
-#   %b Helpfulness:
-#   = @tip.helpfulness
-# %p
-#   %b Tag:
-#   = @tip.tag

= link_to 'Edit', edit_tip_path(@tip)
\|
= link_to 'Back', tips_path